### PR TITLE
P3 preview

### PR DESCRIPTION
**Pull request by manolo**
Connects to #vaadin/components-team-tasks#368

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/19)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[README.md, line 3 at r1](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/19#-LFNBBUS7iJpdxQNXxV7:-LFNBBUS7iJpdxQNXxV8:b-qwa64f) ([raw file](https://github.com/vaadin/vaadin-development-mode-detector/blob/e51fcd79d80028c8a6a6a73b8ecb1cf3e1b52882/README.md#L3)):*
> ```Markdown
> Utility method for detecting that an application using Vaadin Elements is running in development mode
> 
> ### Polymer 3 publishing
> ```

This can be removed now that `

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/19)*

**Comment by tomivirkki** [comment]
*[package.json, line 3 at r1](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/19#-LFNBZOcEiezZET4ONOt:-LFNBZOcEiezZET4ONOu:bfco66s) ([raw file](https://github.com/vaadin/vaadin-development-mode-detector/blob/e51fcd79d80028c8a6a6a73b8ecb1cf3e1b52882/package.json#L3)):*
> ```JSON
> {
>   "name": "@vaadin/vaadin-development-mode-detector",
>   "version": "1.0.3-pre.6",
> ```

Should not say "pre" in master

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/19)*

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @tomivirkki)

---

*[package.json, line 3 at r1](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/19#-LFNBZOcEiezZET4ONOt:-LFNVv3J8RBKgIUK-lo0:b-896fix) ([raw file](https://github.com/vaadin/vaadin-development-mode-detector/blob/e51fcd79d80028c8a6a6a73b8ecb1cf3e1b52882/package.json#L3)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Should not say "pre" in master
</blockquote></details>

Done.

---

*[README.md, line 3 at r1](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/19#-LFNBBUS7iJpdxQNXxV7:-LFNWNqV1Stw9gVb0oKc:b-896fix) ([raw file](https://github.com/vaadin/vaadin-development-mode-detector/blob/e51fcd79d80028c8a6a6a73b8ecb1cf3e1b52882/README.md#L3)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This can be removed now that `
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/19)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/19#-:-LFR5BUEEvyVABG6IUFm:bnfp4nl)*

**Pull request merged**
