### PR TITLE
load dev-mode code from source code comments (removed by minification)

### LINKED ISSUE #21: the latest version from npm (1.1.0-alpha2) does not work with Polymer CLI in P3 projects
When creating a Polymer 3 project with the `polymer init` command from Polymer CLI 1.7.7 (currently latest), adding a Vaadin component there, and starting the project locally with `npm start`, the dev mode detector yields a false negative result and does not collect any usage stats (**it wrongly detects that the project runs in production when it actually is in development**).

Steps to reproduce:
 - install `polymer-cli` 1.7.7 or newer (the issue might as well have appeared in earlier versions)
 - create a new Polymer 3 project from the Polymer Starter Kit: `polymer init polymer-3-starter-kit`
 - install a Vaadin component: `npm i -s @vaadin/vaadin-button` (that pulls in the latest version of `@vaadin/vaadin-development-mode-detector#1.1.0-alpha2`)
 - add the installed component into the project (e.g. in `src/my-app.js`):
    ````javascript
    import '@vaadin/vaadin-button/vaadin-button.js';
    
    ...
    <vaadin-button>Click Me</vaadin-button>
    ...
    ````
- start the project locally in the dev mode: `npm start` and open it in the browser
- open the console and check the value of `window.Vaadin.developmentMode`. See that it's `false`.

### PR DESCRIPTION
**Pull request by vlukashov**
- change the dev mode detection: remove 'is bundled' check, add 'is minified' check
 - remove dev mode code loading from HTML imports / ES modules / etc
 - add dev mode code loading from source code comments
 - started a new major (2.0.0)

Fixes #21

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22)

### CODE REVIEW

**Review by web-padawan — APPROVED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22#-LHqc_l90H_e1Nb7jc38:-LHqc_l90H_e1Nb7jc39:b6u3bgy) (no related file):*
BTW, since the actual import of lazy loaded code (e. g. usage-statistics or license-checker) is now dropped, should we also submit a PR to https://github.com/vaadin/vaadin-element-mixin?

---
___
*[.gitignore, line 4 at r1](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22#-LHqd-dR9R5Yih7IaORd:-LHqd-dR9R5Yih7IaORe:bv64ful) ([raw file](https://github.com/vaadin/vaadin-development-mode-detector/blob/d557dad1719550ae350bcf8e91f419e50f01a340/.gitignore#L4)):*
> ```
> bower_components
> build
> .vscode
> ```

BTW, I suggest using `
___
*[README.md, line 10 at r1](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22#-LHqdNl81Mxr4rr-jdzH:-LHqdNl81Mxr4rr-jdzI:b2nhbfk) ([raw file](https://github.com/vaadin/vaadin-development-mode-detector/blob/d557dad1719550ae350bcf8e91f419e50f01a340/README.md#L10)):*
> ```Markdown
> 1. Run `npm install`
> 1. Run `bower install`
> 1. Run `npm start`
> ```

BTW
___
*[vaadin-development-mode-detector.html, line 54 at r1](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22#-LHqe0Pk9QIV8HGQM0AF:-LHqe0Pk9QIV8HGQM0AG:b-fsf6cq) ([raw file](https://github.com/vaadin/vaadin-development-mode-detector/blob/d557dad1719550ae350bcf8e91f419e50f01a340/vaadin-development-mode-detector.html#L54)):*
> ```HTML
>       try {
>         // requires CSP: script-src 'unsafe-eval'
>         callback = new Function(match[1]);
> ```

BTW how does this work with polyserve transpilation, especially in IE11? Does it pick up that uncommented code?

**Review by vlukashov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22#-LHqc_l90H_e1Nb7jc38:-LHqsr404dL8q9aOLYCP:b-m111iv) (no related file):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW, since the actual import of lazy loaded code (e. g. usage-statistics or license-checker) is now dropped, should we also submit a PR to https://github.com/vaadin/vaadin-element-mixin?
</blockquote></details>

Yes. Once we've this PR is merged into master.

---
___
*[vaadin-development-mode-detector.html, line 54 at r1](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22#-LHqe0Pk9QIV8HGQM0AF:-LHqsdIT642raRC0cD4y:b8t34n6) ([raw file](https://github.com/vaadin/vaadin-development-mode-detector/blob/d557dad1719550ae350bcf8e91f419e50f01a340/vaadin-development-mode-detector.html#L54)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW how does this work with polyserve transpilation, especially in IE11? Does it pick up that uncommented code?
</blockquote></details>

This does not do any transpilation. The code inside the comments has to be transpiled in advance.

**Review by web-padawan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by yuriy-fix — APPROVED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22)* status: all files reviewed, 1 unresolved discussion (waiting on @vlukashov)

___
*[package.json, line 3 at r1](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22#-LJDwV_P8bcJC3rqBvoO:-LJDwV_P8bcJC3rqBvoP:b-c71y7h) ([raw file](https://github.com/vaadin/vaadin-development-mode-detector/blob/d557dad1719550ae350bcf8e91f419e50f01a340/package.json#L3)):*
> ```JSON
> {
>   "name": "@vaadin/vaadin-development-mode-detector",
>   "version": "2.0.0-alpha3",
> ```

Nit: would be nice to merge without squashing to follow the commit hashes for tags.

**Review by web-padawan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by manolo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @YuriyVaadin, @web-padawan, and @vlukashov)

___
*[README.md, line 19 at r3](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22#-LJOAa3a33ugJJGpkbLl:-LJOAa3a33ugJJGpkbLm:b-6z5hpy) ([raw file](https://github.com/vaadin/vaadin-development-mode-detector/blob/e01704c234239213f4d3979d88b427671c8a6f99/README.md#L19)):*
> ```Markdown
> 1. Run `npm run start:prod`
> 1. Open http://localhost:8081/test/index.html
>   1. Verify that `mode` is `production` (orange)
> ```

I get 

```
mode: development

runIfDevelopmentMode: ignored
```

**Review by manolo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @YuriyVaadin, @web-padawan, and @vlukashov)

___
*[vaadin-development-mode-detector.html, line 4 at r3](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22#-LJOC2ft2APKQg83SRaI:-LJOC2ft2APKQg83SRaJ:b-bvur4r) ([raw file](https://github.com/vaadin/vaadin-development-mode-detector/blob/e01704c234239213f4d3979d88b427671c8a6f99/vaadin-development-mode-detector.html#L4)):*
> ```HTML
> (function() {
>   const DEV_MODE_CODE_REGEXP =
>     /\/\*\*\s+vaadin-dev-mode:start([\s\S]*)vaadin-dev-mode:end\s+\*\*\//i;
> ```

Although the hack to detect minimised code is easier to follow, I see complex the implementation, because  you are using a complex multiline that requires a complex regex.

To me a simpler implementation should be just :

```
DEV_MODE_CODE_REGEXP = /\/\*(.*)\*\//;
 /* return false; */
```
___
*[vaadin-development-mode-detector.html, line 45 at r3](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22#-LJOHEbm81wncDBvyyJq:-LJOHEbm81wncDBvyyJr:btui67) ([raw file](https://github.com/vaadin/vaadin-development-mode-detector/blob/e01704c234239213f4d3979d88b427671c8a6f99/vaadin-development-mode-detector.html#L45)):*
> ```HTML
>   }
> 
>   function uncommentAndRun(callback, args) {
> ```

Although this is already scoped, I would move this function inside the `isMinified` block

**Review by web-padawan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @YuriyVaadin, @web-padawan, and @vlukashov)

___
*[README.md, line 19 at r3](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22#-LJOAa3a33ugJJGpkbLl:-LJOSa689UKII6rGnVVY:b-4i0d4t) ([raw file](https://github.com/vaadin/vaadin-development-mode-detector/blob/e01704c234239213f4d3979d88b427671c8a6f99/README.md#L19)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I get 

```
mode: development

runIfDevelopmentMode: ignored
```
</blockquote></details>

can you reinstall dependencies and try again? I'm getting the correct output 
___
*[vaadin-development-mode-detector.html, line 4 at r3](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22#-LJOC2ft2APKQg83SRaI:-LJORUpnBwp-_cxKxIvU:bkd6vn) ([raw file](https://github.com/vaadin/vaadin-development-mode-detector/blob/e01704c234239213f4d3979d88b427671c8a6f99/vaadin-development-mode-detector.html#L4)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Although the hack to detect minimised code is easier to follow, I see complex the implementation, because  you are using a complex multiline that requires a complex regex.

To me a simpler implementation should be just :

```
DEV_MODE_CODE_REGEXP = /\/\*(.*)\*\//;
 /* return false; */
```
</blockquote></details>

this code is also used in vaadin-usage-statistics and we should make sure only comments with special markers are uncommented and passed to `eval()`
___
*[vaadin-development-mode-detector.html, line 45 at r3](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22#-LJOHEbm81wncDBvyyJq:-LJORr0jDkmgQ8OVaA87:byrdt7r) ([raw file](https://github.com/vaadin/vaadin-development-mode-detector/blob/e01704c234239213f4d3979d88b427671c8a6f99/vaadin-development-mode-detector.html#L45)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Although this is already scoped, I would move this function inside the `isMinified` block
</blockquote></details>

it is also needed below, see `window.Vaadin.runIfDevelopmentMode`

**Review by manolo — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22#-:-LJOYRuq4CD3uzBtFJE5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @vlukashov)

___
*[README.md, line 19 at r3](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22#-LJOAa3a33ugJJGpkbLl:-LJOYMac0qAvyS7phLv-:bwve583) ([raw file](https://github.com/vaadin/vaadin-development-mode-detector/blob/e01704c234239213f4d3979d88b427671c8a6f99/README.md#L19)):*
<details><summary><i>Previously, web-padawan (Serhii Kulykov) wrote…</i></summary><blockquote>

can you reinstall dependencies and try again? I'm getting the correct output 
</blockquote></details>

after cleaning node_modules it worked :+1:

**Review by web-padawan — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22)* status: all files reviewed, 1 unresolved discussion (waiting on @vlukashov)

**Review by web-padawan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22)* status: all files reviewed, 1 unresolved discussion (waiting on @vlukashov)

**Review by web-padawan — COMMENTED** [review]
> Dismissed @manolo from a discussion.
> *[Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/22)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
