### PR TITLE
Fix dev mode detector import path detection

### LINKED ISSUE #10: [blocked] Detect bundled P3 application properly
needs https://github.com/vaadin/vaadin-development-mode-detector/issues/17

The current mechanism used for ES modules only takes care of the top-level scripts and is not reliable for the apps. The better option would be to use modulizer with the `--add-import-path` flag for this particular component (development mode probe), this should be supported by the CLI nowadays.

### LINKED ISSUE #17: Fix resources fetching on Polymer 3
https://github.com/vaadin/vaadin-development-mode-detector/pull/16#pullrequestreview-125526687

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #17 
Fixes #10

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/18)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @tomivirkki and @web-padawan)

---

*[vaadin-development-mode-detector.html, line 38 at r3](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/18#-LEtNhAzEN3FeeXEpMO6:-LEtNhAzEN3FeeXEpMO7:b-jqxvjm) ([raw file](https://github.com/vaadin/vaadin-development-mode-detector/blob/824c516bf77a08673894eded71879a940e4fd18c/vaadin-development-mode-detector.html#L38)):*
> ```HTML
>       class DevelopmentModeDetector extends Polymer.Element {
>         static get importMeta() {
>           // magi: return import.meta;
> ```

why not ?

```
/* MAGI ADD START
  return import.meta;
MAGI ADD END */
```

Then you don't need any magi-p3-post file

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/18)*

**Comment by web-padawan** [comment]
Unfortunately, `import.meta` still causes Webpack to fail 😥 

```
ERROR in ./node_modules/@vaadin/vaadin-development-mode-detector/vaadin-development-mode-detector.js 145:21
Module parse failed: Unexpected token (145:21)
You may need an appropriate loader to handle this file type.
|       key: "importMeta",
|       get: function get() {
>         return import.meta;
|       }
|     }, {
 @ ./node_modules/@vaadin/vaadin-element-mixin/vaadin-element-mixin.js 1:0-36:2
 @ ./node_modules/@vaadin/vaadin-button/src/vaadin-button.js
 @ ./node_modules/@vaadin/vaadin-button/theme/lumo/vaadin-button.js
 @ ./node_modules/@vaadin/vaadin-button/vaadin-button.js
 @ ./src/starter-app.js
 @ ./src/index.js
```

Blocked on webpack/webpack#6719, will ping them once again.

**Comment by manolo** [comment]
Review status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @tomivirkki and @web-padawan)

---

*[magi-p3-post.json, line 10 at r3](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/18#-LEwuu9H12Zh6c76VjB4:-LEwuu9H12Zh6c76VjB5:b6mcn9k) ([raw file](https://github.com/vaadin/vaadin-development-mode-detector/blob/824c516bf77a08673894eded71879a940e4fd18c/magi-p3-post.json#L10)):*
> ```JSON
>     "return import.meta;"
>   ],
>   "remove": [
> ```

Not needed anymore when we merge https://github.com/vaadin/magi-cli/pull/17

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/18)*

**Comment by web-padawan** [comment]
Blocked by Polymer/tools#518

**Comment by tomivirkki** [comment]
Review status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @tomivirkki, @manolo, and @web-padawan)

---

*[magi-p3-post.json, line 10 at r3](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/18#-LEwuu9H12Zh6c76VjB4:-LExzYG989Vc171JpmTe:b-896fix) ([raw file](https://github.com/vaadin/vaadin-development-mode-detector/blob/824c516bf77a08673894eded71879a940e4fd18c/magi-p3-post.json#L10)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Not needed anymore when we merge https://github.com/vaadin/magi-cli/pull/17
</blockquote></details>

Done.

---

*[vaadin-development-mode-detector.html, line 38 at r3](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/18#-LEtNhAzEN3FeeXEpMO6:-LExzaEN62AE5JcKjru6:b-yjuwpz) ([raw file](https://github.com/vaadin/vaadin-development-mode-detector/blob/824c516bf77a08673894eded71879a940e4fd18c/vaadin-development-mode-detector.html#L38)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

why not ?

```
/* MAGI ADD START
  return import.meta;
MAGI ADD END */
```

Then you don't need any magi-p3-post file
</blockquote></details>

Can't have import.path before conversion.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/18)*

**Comment by tomivirkki** [comment]
I assume import.path will be blocked for quite a while. I tried using dynamic imports in an eval instead here. The approach is not that clean (it uses _require as a fallback)...but we should either merge this or revert https://github.com/vaadin/vaadin-development-mode-detector/commit/5f3782899eeaa6fa7b110564c25258fb6cb76676 Releasing p3-preview in its current state would probably break some apps.

---







*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/18#-:-LExzq6DDDGqvwEVeXHb:bxewmvy)*

**Comment by web-padawan** [comment]
Reviewed 7 of 10 files at r1, 2 of 2 files at r2, 3 of 3 files at r4.
Review status: all files reviewed, 4 unresolved discussions (waiting on @manolo and @tomivirkki)

---

*[vaadin-development-mode-detector.html, line 37 at r4](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/18#-LEy6oIH9nBekMHLucOt:-LEy6oIH9nBekMHLucOu:b6fcp7r) ([raw file](https://github.com/vaadin/vaadin-development-mode-detector/blob/398380d75654f7f11cb62d0c91f2b59e499a2db1/vaadin-development-mode-detector.html#L37)):*
> ```HTML
> 
>       class DevelopmentModeDetector extends Polymer.Element {
>         
> ```

nit: extra whitespace

---

*[vaadin-development-mode-detector.html, line 90 at r4](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/18#-LEy7UY526vmWBz9J5eD:-LEy7JuC4RuK86SEDxzh:bw39rqh) ([raw file](https://github.com/vaadin/vaadin-development-mode-detector/blob/398380d75654f7f11cb62d0c91f2b59e499a2db1/vaadin-development-mode-detector.html#L90)):*
> ```HTML
> 
>         importAndRun(id, optionalArgument) {
>           let path = "../" + id + "/" + id + ".html";
> ```

note we should still use "assetpath" for Polymer 2. 

Also, without using `static get importMeta` the whole rewriting from `<dom-module id="vaadin-development-mode-probe">` is unnecessary and can be rolled back

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/18)*

**Comment by tomivirkki** [comment]
*[vaadin-development-mode-detector.html, line 90 at r4](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/18#-LEy7UY526vmWBz9J5eD:-LEyHa2L9KNda1cGB1AL:bp1o2r3) ([raw file](https://github.com/vaadin/vaadin-development-mode-detector/blob/398380d75654f7f11cb62d0c91f2b59e499a2db1/vaadin-development-mode-detector.html#L90)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

note we should still use "assetpath" for Polymer 2. 

Also, without using `static get importMeta` the whole rewriting from `<dom-module id="vaadin-development-mode-probe">` is unnecessary and can be rolled back
</blockquote></details>

Ok rebased and rolled back the other changes. I think we should still put this on hold for now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-development-mode-detector/18)*

**Comment by tomivirkki** [comment]
This PR could be closed in favour of https://github.com/vaadin/vaadin-development-mode-detector/pull/22

**Comment by web-padawan** [comment]
Closing in favour of #22 per above comment. That one still uses `eval` but appears to be cleaner.

**Pull request closed without merging**
